### ISSUE TITLE
Possible to run with newer version of k8?

### ISSUE THREAD

**Issue by pushkalkatara** [Deepomatic/shared-gpu-nvidia-k8s-device-plugin#14]
unable to recognize "https://raw.githubusercontent.com/Deepomatic/shared-gpu-nvidia-k8s-device-plugin/v1.10/deepomatic-shared-gpu-nvidia-device-plugin.yml": no matches for kind "DaemonSet" in version "extensions/v1beta1"

**Comment by pushkalkatara** [comment]
`kubectl convert -f <URL> | kubectl create -f ` Helped.

**Comment by thomas-riccardi** [comment]
Hi @pushkalkatara , thanks for the issue and workaround.

We'll resynchronize with upstream nvidia device plugin once they release 1.0.0.
