### ISSUE TITLE
kubectl describe nodes doesn't read GPU.

### ISSUE THREAD

**Issue by pushkalkatara** [Deepomatic/shared-gpu-nvidia-k8s-device-plugin#15]
```Allocatable:
  cpu:                        8
  deepomatic.com/shared-gpu:  0
  ephemeral-storage:          137289078148
  hugepages-1Gi:              0
  hugepages-2Mi:              0
  memory:                     7912776Ki
  nvidia.com/gpu:             1
  pods:                       110
```

**Comment by pushkalkatara** [comment]
If i use nvidia.com/gpu it shows 1 GPU but not in the case of deepomatic.com/shared-gpu, i.e.showing '0'

**Comment by thomas-riccardi** [comment]
Hi @pushkalkatara

What version of the official upstream nvidia device plugin did you use?
Could you try with [nvidia/k8s-device-plugin:1.10-ubuntu16.04](https://hub.docker.com/layers/nvidia/k8s-device-plugin/1.10-ubuntu16.04/images/sha256-7a806cfcb8ff641b4b62a16007dd94b444f34f31c8920c1732e902ed6f343615?context=explore) ? it's the base version we forked this project from.
(you'll need to restart the node to flush the declared extended resources).

Also, what are the logs for `deepomatic-shared-gpu-nvidia-device-plugin-daemonset-xxxxx` ?
