### ISSUE TITLE
not working when using alongside NVIDIA official plugin

### ISSUE THREAD

**Issue by nmarandi** [Deepomatic/shared-gpu-nvidia-k8s-device-plugin#17]
not working when I use shared-gpu-nvidia-k8s-device-plugin alongside [NVIDIA/k8s-device-plugin](https://github.com/NVIDIA/k8s-device-plugin) with [Preventing unprivileged access to GPUs in Kubernetes](https://docs.google.com/document/d/1zy0key-EL6JH50MZgwg96RPYxxXXnVUdxLZwGiyqLd8/edit#heading=h.jw5js7865egx).

helm install \
    --version=0.10.0 \
    --generate-name \
    --set securityContext.privileged=true \
    --set deviceListStrategy=volume-mounts \
    nvdp/nvidia-device-plugin

"**/etc/nvidia-container-runtime/config.toml**" content:
```
disable-require = false
#swarm-resource = "DOCKER_RESOURCE_GPU"
accept-nvidia-visible-devices-envvar-when-unprivileged = false
accept-nvidia-visible-devices-as-volume-mounts = true

[nvidia-container-cli]
#root = "/run/nvidia/driver"
#path = "/usr/bin/nvidia-container-cli"
environment = []
#debug = "/var/log/nvidia-container-toolkit.log"
#ldcache = "/etc/ld.so.cache"
load-kmods = true
#no-cgroups = false
#user = "root:video"
ldconfig = "@/sbin/ldconfig.real"

[nvidia-container-runtime]
#debug = "/var/log/nvidia-container-runtime.log"
```

**Comment by thomas-riccardi** [comment]
Our `deepomatic/shared-gpu-nvidia-k8s-device-plugin` fork predates these new features of nvidia device plugin; I'm not surprised it doesn't work as expected.

We currently have no plan to rebase against a newer version of nvidia device plugin, but if you need that it should not be too much work: the diff with upstream is relatively small.
